import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner"
import { ImageKitProvider } from '@imagekit/next';
import AuthProvider from "@/providers/AuthProvider";
import { DeepgramContextProvider } from "@/providers/DeepgramContextProvider";
import { MicrophoneContextProvider } from "@/providers/MicrophoneContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ImageKitProvider urlEndpoint={process.env.NEXT_PUBLIC_URL_ENDPOINT}>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <main>
              <MicrophoneContextProvider>
                <DeepgramContextProvider>{children}</DeepgramContextProvider>
              </MicrophoneContextProvider>
              <Toaster />
            </main>
          </body>
        </ImageKitProvider>
      </AuthProvider>
    </html>
  );
}
